dwc_eqos - Load ACPI configuration information
worproject/Rockchip-Windows-Drivers pull request #27
Opened 2023-12-30 23:10 UTC by idigdoug

Changes to acpiutil:

- `acpiutil.hpp` depends on definitions from `acpiioct.h`, so `#include` it.
- Fix code analysis warnings about SAL annotations.
- Make `AcpiEvaluateMethod` be public.
- Fix C++ conformance issues with goto jumping past variable initialization.

Changes to driver:

- Define a DeviceConfig struct with all of the configuration information.
- Pass DeviceConfig to queues.
- Queues use DeviceConfig instead of constants.
- Initialize DeviceConfig based on feature registers and ACPI.

Notes:

- Current ACPI sets mixed-burst=1, tso=1, wr_osr_lmt=4, rd_osr_lmt=8, blen=16,8,4.
- NetBSD driver references other settings that are not present in the current ACPI, and sets defaults for them: pbl=8, txpbl=8, rxpbl=8, fixed-burst=0.
- I invented a new value `pblx8` (default = 1) to control whether the X8 flag is set. Existing code assumes that it is set.
- I don't use the `tso` value for anything. I assume it is to enable/disable TCP segmentation offload, which seems more appropriate to configure in the registry.
- The docs say that mixed-burst=1 should translate into FB=0 (same as fixed-burst=0), but the NetBSD driver translates mixed-burst=1 into Reserved14=1. I'll keep that behavior since it doesn't seem to cause any harm.

2023-12-30 23:42 UTC, mariobalanica requested changes

2023-12-30 23:42 UTC, mariobalanica commented on drivers/net/dwc_eqos/_acpiutil.cpp
You can include acpiutil.cpp directly in the project file.

2023-12-30 23:45 UTC, mariobalanica commented on drivers/net/dwc_eqos/_acpiutil.cpp
Unless you wanted to benefit from precomp? But it looks a bit odd to me to have underscore prefixed source files like this.

2023-12-31 00:29 UTC, idigdoug commented on drivers/net/dwc_eqos/_acpiutil.cpp
You get an error if you have enabled precomp for the project and then a .cpp file doesn't include precomp.h as the first thing.

Yeah, I can change the settings on a file-by-file basis... but I hate doing that.

2023-12-31 00:46 UTC, mariobalanica commented on drivers/net/dwc_eqos/_acpiutil.cpp
Ah, I see now.

2023-12-31 00:46 UTC, mariobalanica approved these changes

2023-12-31 04:46 UTC, merged